### ISSUE TITLE
update ceph object class interface growth chart

### ISSUE THREAD

**Issue by dotnwat** [noahdesu/zlog-popper#8]

**Comment by michaelsevilla** [comment]
We also need the script/data necessary for generating this graph.

**Comment by dotnwat** [comment]
I tried to automate it a while back, but it failed as the process was largely manual inspection of code and git logs.

**Comment by dotnwat** [comment]
https://github.com/noahdesu/zlog-popper/blob/master/experiments/objclass-dev/visualize.ipynb

**Comment by ivotron** [comment]
This is cool! Did you count the classes by checking out commits of ceph at
those dates and then eyeballing the code? We might be able to automate that

**Comment by dotnwat** [comment]
I added a description to the ipython notebook about the methodology. i think it could be automated.

**Comment by ivotron** [comment]
Oh, I see, nice! That should be enough IMO.
